/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Image;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Mulay
 */
public class VentanaAhorcado extends javax.swing.JFrame {

    String palabraOculta = "CETYS";
    
    String [] listaPalabras = {"MAMUT", "PANTANO", "ARBOL","CALABACIN", "SAHARA"};
    
    int numeroFallos = 0; //cada vez que fallamos
    boolean partidaTerminada = false; //la partida ha terminado
    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {
        initComponents(); //inicializamos los botones y se ponga todo en su sitio
        dibujaImagen(0); //dibujamos la imagen correspondiente al cero
        palabraOculta = eligePalabraOculta(listaPalabras); //elige una palabra
        escribeGuionesEnPantalla(); //escribe tantos guiones y espacios como tenga la palabra oculta
        //System.out.print(palabraOculta);  lo uso para hacer pruebas
    }
    
    
    //Elige una palabra aleatoria
    private String eligePalabraOculta( String [] lista){
        Random aleatorio = new Random();
        return lista[ aleatorio.nextInt(lista.length) ];
    }
     
    
    //Auxiliar es, Auxiliar igual a Auxiliar mas "_ " tantas veces como letras 
    //tenga la palabra oculta
    private void escribeGuionesEnPantalla(){
        String auxiliar = ""; //creamos un auxiliar
        for (int i=0; i< palabraOculta.length(); i++){
            auxiliar = auxiliar + "_ ";
        }
        Pantalla.setText(auxiliar); //guiones del auxiliar
    }
    
 
    private void chequeaLetra(String letra){
        letra = letra.toUpperCase();
        
        StringBuilder palabraConGuiones = new StringBuilder(Pantalla.getText());
        if (palabraOculta.contains(letra)){
            for (int i=0; i< palabraOculta.length(); i++){
                if (palabraOculta.charAt(i) == letra.charAt(0)){
                    palabraConGuiones.setCharAt(2*i,letra.charAt(0));
                }
            }
            Pantalla.setText(palabraConGuiones.toString());
        }
        else{
            numeroFallos++;//me incrementa el numero de fallos en 1
            
        }
        dibujaImagen(numeroFallos); //si falla me saca una imagen
    }

    private void dibujaImagen(int numeroImagen){
        
        URL nombreImagen = null;
        switch (numeroImagen){
            case 0: nombreImagen = getClass().getResource("/imagenes/Ahorcado1.jpg"); break;
            case 1: nombreImagen = getClass().getResource("/imagenes/Ahorcado2.jpg"); break;
            case 2: nombreImagen = getClass().getResource("/imagenes/Ahorcado3.jpg"); break;
            case 3: nombreImagen = getClass().getResource("/imagenes/Ahorcado4.jpg"); break;
            case 4: nombreImagen = getClass().getResource("/imagenes/Ahorcado5.jpg"); break;
            case 5: nombreImagen = getClass().getResource("/imagenes/Ahorcado6.jpg"); break;
            case 6: nombreImagen = getClass().getResource("/imagenes/Ahorcado7.jpg"); break;
            default: nombreImagen = getClass().getResource("/imagenes/AhorcadoFin.jpg");
        }
        
        int ancho = panelAhorcado.getWidth();
        int alto = panelAhorcado.getHeight();
        
        ImageIcon miImagen = new ImageIcon (new ImageIcon(nombreImagen).getImage().getScaledInstance(ancho, alto,Image.SCALE_DEFAULT));
        panelAhorcado.setIcon(miImagen);
    }
    
    private void chequeaBoton (JButton miBoton){
        //si no has perdido la partida siguen igual, y sino se desactivan
        miBoton.setEnabled(false);
        chequeaLetra(miBoton.getText());
        
    }
    //cuando he perdido que bloquee los botones
    
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JLabel();
        panelAhorcado = new javax.swing.JLabel();
        letra1 = new javax.swing.JButton();
        letra2 = new javax.swing.JButton();
        letra3 = new javax.swing.JButton();
        letra4 = new javax.swing.JButton();
        letra5 = new javax.swing.JButton();
        letra6 = new javax.swing.JButton();
        letra7 = new javax.swing.JButton();
        letra8 = new javax.swing.JButton();
        letra9 = new javax.swing.JButton();
        letra10 = new javax.swing.JButton();
        letra11 = new javax.swing.JButton();
        letra12 = new javax.swing.JButton();
        letra13 = new javax.swing.JButton();
        letra14 = new javax.swing.JButton();
        letra15 = new javax.swing.JButton();
        letra16 = new javax.swing.JButton();
        letra17 = new javax.swing.JButton();
        letra18 = new javax.swing.JButton();
        letra19 = new javax.swing.JButton();
        letra20 = new javax.swing.JButton();
        letra21 = new javax.swing.JButton();
        letra22 = new javax.swing.JButton();
        letra23 = new javax.swing.JButton();
        letra24 = new javax.swing.JButton();
        letra25 = new javax.swing.JButton();
        letra26 = new javax.swing.JButton();
        letra27 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pantalla.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Pantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pantalla.setText("_ _ _ _ _ ");

        panelAhorcado.setText("jLabel2");

        letra1.setText("A");
        letra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra1MousePressed(evt);
            }
        });

        letra2.setText("B");
        letra2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra2MousePressed(evt);
            }
        });
        letra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra2ActionPerformed(evt);
            }
        });

        letra3.setText("C");
        letra3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra3MousePressed(evt);
            }
        });

        letra4.setText("D");
        letra4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra4MousePressed(evt);
            }
        });

        letra5.setText("E");
        letra5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra5MousePressed(evt);
            }
        });

        letra6.setText("G");
        letra6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra6MousePressed(evt);
            }
        });

        letra7.setText("F");
        letra7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra7MousePressed(evt);
            }
        });

        letra8.setText("H");
        letra8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra8MousePressed(evt);
            }
        });

        letra9.setText("I");
        letra9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra9MousePressed(evt);
            }
        });

        letra10.setText("J");
        letra10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra10MousePressed(evt);
            }
        });

        letra11.setText("K");
        letra11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra11MousePressed(evt);
            }
        });

        letra12.setText("L");
        letra12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra12MousePressed(evt);
            }
        });

        letra13.setText("N");
        letra13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra13MousePressed(evt);
            }
        });

        letra14.setText("M");
        letra14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra14MousePressed(evt);
            }
        });

        letra15.setText("Ñ");
        letra15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra15MousePressed(evt);
            }
        });

        letra16.setText("O");
        letra16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra16MousePressed(evt);
            }
        });

        letra17.setText("P");
        letra17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra17MousePressed(evt);
            }
        });

        letra18.setText("Q");
        letra18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra18MousePressed(evt);
            }
        });

        letra19.setText("R");
        letra19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra19MousePressed(evt);
            }
        });

        letra20.setText("T");
        letra20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra20MousePressed(evt);
            }
        });

        letra21.setText("S");
        letra21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra21MousePressed(evt);
            }
        });

        letra22.setText("U");
        letra22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra22MousePressed(evt);
            }
        });

        letra23.setText("V");
        letra23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra23MousePressed(evt);
            }
        });

        letra24.setText("W");
        letra24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra24MousePressed(evt);
            }
        });

        letra25.setText("X");
        letra25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra25MousePressed(evt);
            }
        });

        letra26.setText("Y");
        letra26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra26MousePressed(evt);
            }
        });

        letra27.setText("Z");
        letra27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra27MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(letra8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(letra15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(letra22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(letra25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra26, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(letra27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra26, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letra1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra1MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra1MousePressed

    private void letra2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra2MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra2MousePressed

    private void letra3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra3MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra3MousePressed

    private void letra4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra4MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra4MousePressed

    private void letra5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra5MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra5MousePressed

    private void letra6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra6MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra6MousePressed

    private void letra7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra7MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra7MousePressed

    private void letra8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra8MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra8MousePressed

    private void letra9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra9MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra9MousePressed

    private void letra10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra10MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra10MousePressed

    private void letra11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra11MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra11MousePressed

    private void letra12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra12MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra12MousePressed

    private void letra13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra13MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra13MousePressed

    private void letra14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra14MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra14MousePressed

    private void letra15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra15MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra15MousePressed

    private void letra16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra16MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra16MousePressed

    private void letra17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra17MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra17MousePressed

    private void letra18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra18MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra18MousePressed

    private void letra19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra19MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra19MousePressed

    private void letra20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra20MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra20MousePressed

    private void letra21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra21MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra21MousePressed

    private void letra22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra22MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra22MousePressed

    private void letra23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra23MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra23MousePressed

    private void letra24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra24MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra24MousePressed

    private void letra25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra25MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra25MousePressed

    private void letra27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra27MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra27MousePressed

    private void letra26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra26MousePressed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra26MousePressed

    private void letra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra2ActionPerformed
        chequeaBoton((JButton)evt.getSource());
    }//GEN-LAST:event_letra2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pantalla;
    private javax.swing.JButton letra1;
    private javax.swing.JButton letra10;
    private javax.swing.JButton letra11;
    private javax.swing.JButton letra12;
    private javax.swing.JButton letra13;
    private javax.swing.JButton letra14;
    private javax.swing.JButton letra15;
    private javax.swing.JButton letra16;
    private javax.swing.JButton letra17;
    private javax.swing.JButton letra18;
    private javax.swing.JButton letra19;
    private javax.swing.JButton letra2;
    private javax.swing.JButton letra20;
    private javax.swing.JButton letra21;
    private javax.swing.JButton letra22;
    private javax.swing.JButton letra23;
    private javax.swing.JButton letra24;
    private javax.swing.JButton letra25;
    private javax.swing.JButton letra26;
    private javax.swing.JButton letra27;
    private javax.swing.JButton letra3;
    private javax.swing.JButton letra4;
    private javax.swing.JButton letra5;
    private javax.swing.JButton letra6;
    private javax.swing.JButton letra7;
    private javax.swing.JButton letra8;
    private javax.swing.JButton letra9;
    private javax.swing.JLabel panelAhorcado;
    // End of variables declaration//GEN-END:variables
}
